<?php

/**
 * @file
 * Contains ib3_toolkit.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ib3_toolkit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ib3_toolkit module.
    case 'help.page.ib3_toolkit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Collection of services and traits to make life simple.') . '</p>';
      return $output;

    default:
  }
}
